### ISSUE TITLE
Partner Signup Form

### ISSUE THREAD

**Issue by ghost** [monetcap/uikit-react-boilerplate#10]
- [x] Create `uk-modal` for form
- [x] Create form `inputs`
- [x] on submit success page
- [x] Submit Form Submissions to Google Sheet (requires #23)

**Comment by arisaves** [comment]
I used this package successfully: https://www.npmjs.com/package/html-form-send-email-via-google-script-without-server

There is a caveat for React, I will share it with my next commit.
