### ISSUE TITLE
FE Bug: iOs button override

### ISSUE THREAD

**Issue by arisaves** [monetcap/uikit-react-boilerplate#13]
Why Apple gotta do this, mane? Try to do a fixo on this ugglo bugglo. 

To reproduce: Make sure you have iOs Simulator/xCode -- open an iphone simulator and navi to the frontend.
<img width="355" alt="screen shot 2019-02-05 at 10 19 11 pm" src="https://user-images.githubusercontent.com/886231/52322770-91893680-2997-11e9-8eb0-47e743a26d01.png">

**Comment by ghost** [comment]
waiting for review from @arisaves but I believe this was an issue with the button being a form `input` element and not a `button` element. See 3f29f60 for details....
