### ISSUE TITLE
FE Feature: Jump-links to divs and forms from mobile menu (react-router)

### ISSUE THREAD

**Issue by arisaves** [monetcap/uikit-react-boilerplate#14]
Add react-router so that we can use #anchor links to nav to sections on mobile.
<img width="337" alt="screen shot 2019-02-06 at 12 54 31 pm" src="https://user-images.githubusercontent.com/886231/52369645-6beb4400-2a0e-11e9-9af2-c240ac2c0b8d.png">

**Comment by ghost** [comment]
requires #24
