### ISSUE TITLE
Google Sheets Form Submissions Sender

### ISSUE THREAD

**Issue by ghost** [monetcap/uikit-react-boilerplate#23]
We need to create a function/React-Component that get passed data to be appended to a Google Sheet's Document.

```javascript
function appendDataToGoogleSheet(data, sheetURL) {
    axios.post(sheetURL, { data: data })
}

being able to pass a SpreadsheetURL and a JSON data object to the function is paramount to being able to reuse this function across our project. For example, within our MSF, Contact Form, and Partners Form.

**Comment by arisaves** [comment]
Kaden, we have something for this already. I will update this ticket with details but I've been using https://www.npmjs.com/package/html-form-send-email-via-google-script-without-server -- please let me know if you have an issue with using this approach for now. It will be more expedient for getting to MVP and I have tested it successfully with my partner form.

**Comment by arisaves** [comment]
Kaden, we have something for this already. I will update this ticket with details but I've been using https://www.npmjs.com/package/html-form-send-email-via-google-script-without-server -- please let me know if you have an issue with using this approach for now. It will be more expedient for getting to MVP and I have tested it successfully with my partner form.

There is a nuance for react forms that I'm trying to dig up in GH; will attach to this ticket.
