### ISSUE TITLE
FE Feature: Skeleton the multistep form

### ISSUE THREAD

**Issue by arisaves** [monetcap/uikit-react-boilerplate#3]
Create a high level skeleton for the multistep form; we should be able to make use of uk-modal for this but other packages are ok if they help you. I will try to model this on the backend so form fields are organized by pages that you can count/loop through to display the status changes. Feel free to get creative here if you see opportunities to improve on the design depicted in the wireframes.

**Comment by ghost** [comment]
components will use these `uikit` components to have a "multistep/wizard" functionality:
https://getuikit.com/docs/tab#left-right-modifiers
https://getuikit.com/docs/switcher#switcher-and-tab

**Comment by KadenLNelson** [comment]
https://getuikit.com/docs/switcher#switcher-and-tab

**Comment by ghost** [comment]
https://getuikit.com/docs/modal is going to be used to provide an immersive experience for the user after they click the `Apply Now` button on the Hero

**Comment by ghost** [comment]
- [ ] #6
