### ISSUE TITLE
WAVE errors: missing form labels + an empty button

### ISSUE THREAD

**Issue by arisaves** [monetcap/uikit-react-boilerplate#30]
To reproduce, install a WAVE plugin on your browser du jour + smash that button when viewing the monetcap site.

![screen shot 2019-02-19 at 12 10 47 pm](https://user-images.githubusercontent.com/886231/53034144-9989b180-3440-11e9-9edd-d17d45f3bb5f.png)

**Comment by KadenLNelson** [comment]
https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh?hl=en-US

this one?

**Comment by KadenLNelson** [comment]
does this work?

**Comment by arisaves** [comment]
Yup, thats the one I use!

**Comment by ghost** [comment]
https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh?hl=en-US this one?
